#!/usr/bin/env bash

icone="${HOME}/.local/share/icons/Newaita/devices/64/video-display.svg"
volume=$(pactl list sinks | grep '^[[:space:]]Volume:' |     head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

notify-send -i $icone "Volume: $volume"
