#!/usr/bin/env bash

echo "🎨️"
echo "---"
echo "🌍️ Unsplash Download | terminal=false bash='${HOME}/bin/unsplash.sh --download'"
echo "💫️ Unsplash Random | terminal=false bash='${HOME}/bin/unsplash.sh --random'"
echo "💥️ Wallhaven Remove | terminal=false bash='${HOME}/bin/wallhaven.sh --delete'"
echo "---"
echo "🌍️ Wallhaven Download | terminal=false bash='${HOME}/bin/wallhaven.sh'"
echo "💫️ Wallhaven Random | terminal=false bash='${HOME}/bin/wallhaven.sh --random'"
echo "💥️ Wallhaven Remove | terminal=false bash='${HOME}/bin/wallhaven.sh --delete'"
#echo "🌍️ Unsplash Clean | terminal=false bash='${HOME}/bin/unsplash.sh --clean'"
#echo "🌍️ WallHaven Download | terminal=false bash='${HOME}/bin/wallhaven.sh --download'"
#echo "🌍️ WallHaven Random | terminal=false bash='${HOME}/bin/wallhaven.sh --random'"
#echo "🌍️ WallHaven Clean | terminal=false bash='${HOME}/bin/wallhaven.sh --clean'"
