version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ~/htdocs:/code
            - ~/docker/confs/nginx.conf:/etc/nginx/conf.d/default.conf
            - ~/docker/certs:/etc/ssl/nginx
		restart: unless-stopped

    php:
        container_name: php
        image: php:fpm
        depends_on:
            - nginx
        ports:
            - "9000:9000"
        build:
            context: ../../dockerfile/drupal/
            dockerfile: php
        volumes:
            - ~/htdocs:/code
            - ~/docker/confs/phplog.conf:/usr/local/etc/php-fpm.d/log.conf
            - ~/docker/confs/php.conf:/usr/local/etc/php-fpm.d/php.conf
            - ~/docker/confs/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ~/docker/confs/fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
		restart: unless-stopped

    mysql:
        container_name: mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        build:
            context: ../../dockerfile/drupal/
            dockerfile: mysql
        volumes:
            - ~/docker/data/mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=drupal
			- MYSQL_PASSWORD=senha
            - MYSQL_ROOT_PASSWORD=senha
		restart: unless-stopped
