#!/usr/bin/env bash
################################################################################
#                                                                              #
# Arquivo: ~/.config/rofi/scripts/apps                                         #
#                                                                              #
# Autor: Lucas Saliés Brum a.k.a. sistematico <lucas@archlinux.com.br>         #
#                                                                              #
# Criado em: 30/04/2019 13:55:09                                               #
# Modificado em: 2021-08-13 20:15:12Z                                          #
#                                                                              #
# Este trabalho está licenciado com uma Licença Creative Commons               #
# Atribuição 4.0 Internacional                                                 #
# http://creativecommons.org/licenses/by/4.0/                                  #
#                                                                              #
################################################################################

apps=("Thunar" "Browsers" "Terminais" "Editores" "Database" "Telegram" "LXTask")
browser=("Google Chrome" "Mozilla Firefox")
term=("st" "Alacritty" "Kitty" "urxvt")
edit=("VS Code" "Atom" "PHPStorm" "WebStorm")
data=("DataGrip" "SQLiteBrowser" "TablePlus")

res=$(printf "%s\n" "${apps[@]}" | rofi -dmenu -p "Rofi Apps" -bw 0 -l "${#apps[@]}" -separator-style none -location 0 -theme-str 'window {width: 120px;}' -hide-scrollbar -padding 1)

if [ ! -z $res ]; then
    case $res in
        "Thunar") thunar ;;
        "Browsers")
            browsers=$(printf "%s\n" "${browser[@]}" | rofi -dmenu -p "Browsers" -bw 0 -l "${#browser[@]}" -separator-style none -location 0 -theme-str 'window {width: 150px;}' -hide-scrollbar -padding 1)
            
            case $browsers in
                "Google Chrome") google-chrome-stable ;;
                "Mozilla Firefox") firefox ;;
            esac
        ;;
        "Terminais") 
            terminais=$(printf "%s\n" "${term[@]}" | rofi -dmenu -p "Terminais" -bw 0 -l "${#term[@]}" -separator-style none -location 0 -theme-str 'window {width: 140px;}' -hide-scrollbar -padding 1)
            
            case $terminais in
                "st") st ;;
                "Alacritty") alacritty ;;
                "urxvt") urxvt ;;
            esac
        ;;
        "Editores") 
            editores=$(printf "%s\n" "${edit[@]}" | rofi -dmenu -p "Editores" -bw 0 -l "${#edit[@]}" -separator-style none -location 0 -theme-str 'window {width: 130px;}' -hide-scrollbar -padding 1)
            
            case $editores in
                "VS Code") code --disable-gpu ;;
                "Atom") atom ;;
                "PHPStorm") phpstorm ;;
                "WebStorm") webstorm ;;
            esac
        ;;
        "Database") 
            database=$(printf "%s\n" "${data[@]}" | rofi -dmenu -p "Database" -bw 0 -l "${#data[@]}" -separator-style none -location 0 -theme-str 'window {width: 150px;}' -hide-scrollbar -padding 1)
            
            case $database in
                "DataGrip") datagrip ;;
                "SQLiteBrowser") sqlitebrowser ;;
                "TablePlus") tableplus ;;
            esac
        ;;
        "Telegram") telegram-desktop ;;
        "LXTask") lxtask ;;
        *) $res ;;
    esac
fi
