#!/usr/bin/env bash
################################################################################
#                                                                              #
# Arquivo: ~/.config/rofi/scripts/apps                                         #
#                                                                              #
# Autor: Lucas Saliés Brum a.k.a. sistematico <lucas@archlinux.com.br>         #
#                                                                              #
# Criado em: 30/04/2019 13:55:09                                               #
# Modificado em: 28/09/2021 16:43:44                                           #
#                                                                              #
# Este trabalho está licenciado com uma Licença Creative Commons               #
# Atribuição 4.0 Internacional                                                 #
# http://creativecommons.org/licenses/by/4.0/                                  #
#                                                                              #
################################################################################

apps=("Firefox" "Thunar" "urxvt" "VS Code" "Steam" "Telegram" "LXTask")
res=$(printf "%s\n" "${apps[@]}" | rofi -dmenu -p "Rofi Apps" -bw 0 -l "${#apps[@]}" -separator-style none -location 0 -theme-str 'window {width: 155px;}' -hide-scrollbar -padding 1)

if [ "$res" ]; then
    case "$res" in
        "Firefox") firefox ;;
        "Thunar") thunar ;;
        "urxvt") urxvt ;;
        "VS Code") code ;;
        "Steam") steam ;;
        "Telegram") telegram-desktop ;;
        "LXTask") lxtask ;;
        *) $res ;;
    esac
fi

exit