#!/bin/bash

res=$(echo "firefox;termite;thunar;telegram;vscode;lxtask;deluge" | rofi -sep ";" -dmenu -p "Rofi Apps" -bw 0 -lines 7 -separator-style none -location 0 -width 180 -hide-scrollbar -padding 1)

if [ ! -z $res ]; then
	case $res in
		telegram) i3-msg -q exec --no-startup-id telegram-desktop ;;
		vscode) i3-msg -q exec --no-startup-id code ;;
		*) i3-msg -q "exec --no-startup-id $res" ;;
	esac
fi
