#!/bin/bash

# rofi -show drun -theme-str 'element-icon { size: 1.3em;}' -opacity "80" -lines 8 -line-margin 0 -width 10 -padding 16
#rofi -show drun -theme-str 'element-icon { size: 1.6em;}' -lines 6
rofi -show drun -theme-str 'element-icon { size: 1.6em;}' -lines 5 -width 28
