#!/usr/bin/env bash



#rofi -show drun -font \\"DejaVu 9\\" -run-shell-command '{terminal} -e \\" {cmd}; read -n 1 -s\\"'
#rofi -show drun -terminal urxvt -lines 2 -run-shell-command '{terminal} -e \\" {cmd}; read -n 1 -s\\"'

rofi -show drun -terminal urxvt -lines 2 -run-shell-command '{terminal} -e \\" {cmd}; read -n 1 -s\\"'
