#!/usr/bin/env bash

dir="${HOME}/.config/rofi/scripts/"
oldpwd=$(pwd)
cd $dir
entrada=$(ls $dir | rofi -dmenu -p "Rofi Scripts" -l "$(ls -1 $dir | wc -l)" -show run -opacity "80" -theme-str 'window {width: 20px;}' -padding 16)

if [ "$entrada" ]; then
	./$entrada
fi
cd $oldpwd
